# Generated by Django 3.2.25 on 2026-04-14 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
