# Generated by Django 4.2.7 on 2026-06-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_productmodel_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="id",
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
