# Generated by Django 3.2.25 on 2026-06-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemmodel',
            name='product_id',
            field=models.CharField(max_length=20),
        ),
    ]
