# Generated by Django 3.2.25 on 2026-06-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitemmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemmodel',
            name='product_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cartitemmodel',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
